export const KEYWORDS = [
    [ 'british', 1520 ], [ 'us', 1505 ],
    [ 'soldier', 1113 ], [ 'war', 1101 ],
    [ 'soldiers', 958 ],
    [ 'you', 858 ],      [ 'liberty', 835 ],
    [ 'your', 708 ],     [ 'flag', 704 ],
    [ 'red', 546 ],      [ 'holding', 543 ],
    [ 'german', 523 ],
    [ 'american', 514 ], [ 'man', 504 ],
    [ 'woman', 498 ],    [ 'loan', 489 ],
    [ 'cross', 477 ],    [ 'background', 477 ],
    [ 'french', 462 ],   [ 'victory', 432 ],
    [ 'buy', 430 ],
    [ 'two', 427 ],      [ 'men', 427 ],
    [ 'are', 413 ],      [ 'bonds', 381 ],
    [ 'an', 379 ],       [ 'over', 339 ],
    [ 'his', 315 ],      [ 'up', 315 ],
    [ 'this', 308 ],     [ 'words', 306 ],
    [ 'under', 300 ]
].map(w => w[0])

export const TOPICS = [
    [ "Propaganda", 1789 ],
    [ "Morale and propaganda", 1783 ],
    [ "Fund raising", 1687 ],
    [ "Recruiting and enlistment", 627 ],
    [ "Relief and volunteer organizations", 519 ],
    [ "Reconstruction", 425 ],
    [ "Liberty bonds", 331 ],
    [ "Conservation/Food production", 279 ],
    [ "War production", 254 ],
    [ "Exhibitions, Films, Publications", 250 ],
    [ "Women's War Work", 189 ],
    [ "Women in war", 181 ],
    [ "Troop morale", 147 ],
    [ "International relief", 145 ],
    [ "War Savings Stamps", 140 ],
    [ "Tribute to Allies", 122 ],
    [ "Conservation of natural resources", 119 ],
    [ "Travel", 107 ],
    [ "Health/Industrial Safety", 103 ],
    [ "Food conservation", 102 ],
    [ "Politics", 96 ],
    [ "Careless talk", 78 ],
    [ "Statue of Liberty (New York, N.Y.)", 66 ],
    [ "Education", 62 ],
    [ "Ethnic groups", 49 ],
    [ "Advertisement", 45 ],
    [ "Uncle Sam (Symbolic character) in art", 43 ],
    [ "advertising", 41 ],
    [ "Celebrities", 37 ],
    [ "Civil defense", 36 ],
    [ "Defense Preparedness", 36 ],
    [ "Proclamations", 30 ],
    [ "Exhibitions", 29 ],
    [ "Discharging Soldiers", 27 ],
    [ "Personalities", 26 ],
    [ "Nurses", 26 ],
    [ "Educational", 25 ],
    [ "Ships", 25 ],
    [ "Liberty Bell", 23 ],
    [ "Industrial safety", 17 ],
    [ "Employment", 16 ],
    [ "New Deal Projects", 15 ],
    [ "Shipbuilding", 14 ],
    [ "Thrift Stamps", 14 ],
    [ "Energy conservation", 13 ],
    [ "Transportation", 12 ],
    [ "Prisoners of war", 10 ]
].map(w => w[0])